### ISSUE TITLE
SmallVector implicit copy assignment bug

### ISSUE THREAD

**Issue by gbernstein** [rmjarvis/tmv#23]
When compiling code using SmallVector with a C++-11 standard I am getting errors that indicate that the operator= for this class needs a non-const argument.  The symptom is a compiler error when trying to build a defaulted copy assignment for a class that contains a SmallVector as a member.  Here is some example code that generates the error (different error text for Clang g++ than for Gnu g++):

_EDIT: sorry, I inserted the wrong code..._

```
#include "TMV.h"

using namespace std;

typedef tmv::SmallVector<double,3> MVector;

class MM {
public:
  MVector m;
  MM(const MVector& _m=MVector(0.)): m(_m) {}
  MM& operator=(const MM& rhs)  =default;
  //  {m=rhs.m; return *this;}
};

int
main(int argc,
     char *argv[])
{
  MVector mv(1.);
  MM mm1(mv);
  MM mm2;
  mm2=mm1;
}
```
It looks to me like the solution is to add const to the copy assignment operator in line 200 of TMV_SmallVector.h:

 ```
       inline type& operator=(const type& v2) //***GMB CHANGE 1/24/17
```

That makes the compiler errors go away, but I don't know whether this is non-const for some other good reason and this would break something.  If it's ok, can I make this change and re-scons everything?

**Comment by rmjarvis** [comment]
Sorry, I'm not sure why this (and line 208) didn't have the const.  (Vector is also missing it on 2 of its op= signatures.)  They should have const there.  Nothing breaks in the test suite when I add them, so I'm pretty sure it was just an oversight, not something intentional.

**Comment by rmjarvis** [comment]
This is fixed on master.  It will be included in the next release.
