### ISSUE TITLE
Compiler flags for newest Intel compiler

### ISSUE THREAD

**Issue by gbernstein** [rmjarvis/tmv#24]
When building with Intel icpc version 17.0.4, these warnings are issued:
```
icpc: command line remark #10148: option '-vec-report0' not supported
icpc: command line remark #10411: option '-openmp' is deprecated and will be removed in a future release. Please use the replacement option '-qopenmp'
```

**Comment by rmjarvis** [comment]
Lol.  icpc has always had a different flag for OpenMP than gcc and clang.  So they finally decided to change it to **another** flag that is still different from gcc and clang!  <sigh>

**Comment by rmjarvis** [comment]
Fixed.
