### ISSUE TITLE
Build breaks: NameError: name 'link_name' is not defined

### ISSUE THREAD

**Issue by yurivict** [rmjarvis/tmv#27]
FreeBSD 11.1

**Comment by rmjarvis** [comment]
Yes, it looks like the code only works for MacOS or Linux.  Not FreeBSD.  I suspect the right thing to do would be the same as for Linux, but apparently I've never tried installing on a FreeBSD box.  

Could you check if changing line 129 in src/SConstruct to
```
elif sys.platform.startswith('linux') or sys.platform.startswith('freebsd'):
```
works for you?

**Comment by yurivict** [comment]
Yes, I did just that and it worked.

But now it has built, but can't install. It doesn't recognize DESTDIR:
```
Install file: "lib/libtmv_symband.so.0" as "/usr/local/lib/libtmv_symband.so.0"
scons: *** [/usr/local/include/tmv] /usr/local/include/tmv: Permission denied
scons: *** [/usr/local/lib/libtmv.so.0] /usr/local/lib/libtmv.so.0: Permission denied
scons: *** [/usr/local/lib/libtmv_symband.so.0] /usr/local/lib/libtmv_symband.so.0: Permission denied
```

Could you give me a hint how to fix this?

**Comment by yurivict** [comment]
Another problem is that it doesn't recognize OpenMP library.
```
g++6 -o .sconf_temp/conftest_35 " -L/usr/local/lib -fstack-protector -Wl,-rpath=/usr/local/lib/gcc6 -L/usr/local/lib/gcc6" -fopenmp .sconf_temp/conftest_35.o -Llib -lblas -lpthread
g++6: error:  -L/usr/local/lib -fstack-protector -Wl,-rpath=/usr/local/lib/gcc6 -L/usr/local/lib/gcc6: No such file or directory
```

I think it supplies ```" -L/usr/local/lib -fstack-protector -Wl,-rpath=/usr/local/lib/gcc6 -L/usr/local/lib/gcc6"``` as a single string, and this fails.

**Comment by rmjarvis** [comment]
> There should be a way to supply DESTDIR.

It's called PREFIX here.  You can type `scons -h` for all the various options.  But normally if you don't have sudo-writeable access to /usr/local, you would do `scons PREFIX=/somewhere/else/` to install in a custom location.

Not sure about the quote thing.  That doesn't happen on any of my machines, so maybe that's something different about the FreeBSD OS compared to linux.

**Comment by yurivict** [comment]
SCons is just buggy and not robust. cmake doesn't have such problems.
