### ISSUE TITLE
Make TMV relocatable

### ISSUE THREAD

**Issue by SimonKrughoff** [rmjarvis/tmv#29]
I've noticed that TMV produces links to absolute paths in the install phase.  This means that I can't move the install tree to a different location and expect anything that linked to the symlink to continue to work.  I think changing to use relative paths is a simple way to get that functionality.  Playing with this a little, I think the following diff is (close to?) an implementation that could work.

```diff
diff --git a/src/SConscript b/src/SConscript
index 8b76632..097849f 100644
--- a/src/SConscript
+++ b/src/SConscript
@@ -164,9 +164,17 @@ if env['SHARED']:
         #print 'SymLink: source = ',str(source[0])
         #print 'target = ',str(target[0])
         #print 'LibName = ',env['LibName']
-        t = os.path.abspath(str(target[0]))
+        starting_dir = os.getcwd()
+        t = str(target[0])
+        s = str(source[0])
+        prefix = os.path.commonprefix([os.path.dirname(t), os.path.dirname(s)])
+        os.chdir(prefix)
+        if len(prefix) > 1:
+            t = t[len(prefix)+1:]
+            s = s[len(prefix)+1:]
         if os.path.exists(t): os.remove(t)
-        os.symlink(env['LibName'], t)
+        os.symlink(s, t)
+        os.chdir(starting_dir)
```
If this is acceptable, I can make a PR.

Edit: I believe this same technique is likely to work for making `galsim` relocatable as well.

**Comment by rmjarvis** [comment]
For most purposes, I think the absolute paths are more useful, since then there is less dependence on system variables like DYLD_LIBRARY_PATH, which as you know Mac's have kind of fked with recently.

However, I'd be perfectly fine with this different behavior being a scons option that people can turn on if they want.  e.g. `scons REL_LIB_PATH=True` or something similar.

**Comment by SimonKrughoff** [comment]
For what it's worth, getting this to work on macOS was way harder than just changing the symlinks.  See [here](https://github.com/lsst/tmv/blob/master/ups/eupspkg.cfg.sh#L6) for how I ended up doing it.

Given that, I doubt you want to implement that in `tmv` and `galsim`.  If I'm wrong about that, please let me know.

**Comment by rmjarvis** [comment]
Starting with GalSim v2.0, that won't even depend on TMV anymore, so probably at least this part of your issue will be solved.  And GalSim will use setup.py installation, not SCons.  So probably a whole new panoply of problems for you to deal with.  :)
